### ISSUE TITLE
Proposiciones Lógicas

### ISSUE THREAD

**Issue by Berenice1719** [SistemasTecTlaxiaco/actividad-7-proposiciones-l-gicas-Berenice1719#1]
[Propociciones Logicas..pdf](https://github.com/user-attachments/files/17442581/Propociciones.Logicas.pdf)

**Comment by Victor-noe12** [comment]
Portada:25/25
Procedimiento:25/25
Figuras, Ilustraciones y Fotografías:25/25
Resultados y conclusiones:25/25
Total:100/100

**Comment by josealfredo79** [comment]
bien hecho y revisado...
